-- Drop Fact Tables
DROP TABLE IF EXISTS Ski_Lift_Usage;
DROP TABLE IF EXISTS Slope_to_Lift;
DROP TABLE IF EXISTS Slope_to_Slope;

-- Drop Dimension Tables
DROP TABLE IF EXISTS Junk;
DROP TABLE IF EXISTS Ski_Pass;
DROP TABLE IF EXISTS Ski_Lift;
DROP TABLE IF EXISTS Ski_Slope;
DROP TABLE IF EXISTS Customers;
DROP TABLE IF EXISTS Time;
DROP TABLE IF EXISTS Date;